# Generated by ChatGPT on 2026-07-15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklocation",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="manager_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
