# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='accepted_payment_methods',
            field=models.JSONField(blank=True, default=list, help_text="Keys of payment methods accepted at the register, e.g. ['cash', 'card', 'mobile_money', 'other']"),
        ),
    ]
